# Written by Infrar, inside the directory Infrar owns (.infrar/environment/). This directory
# declares what this repository NEEDS to run (databases, caches, buckets, queues, services),
# by product and version, as OpenTofu. Infrar reads these declarations to realise the
# resources in each namespace the repository is imported into, and keeps them current from
# the Change that moves a `requires:`; nothing here names a namespace, a host, an id or a
# value. Edit freely — Infrar re-reads the files.
#   generated by:  prv-p1-check
#   generated at:  2026-09-15T08:00:00.000Z
#   irp rules:     2

terraform {
  required_version = ">= 1.8.0"
}
